#lang racket

(provide auto-doc-model)

(require scribble/manual
         syntax/parse/define) 

(define-syntax (auto-doc-model stx)
  (syntax-parse stx
    [(_ model-base-path)
     #`(let ()
         (local-require 
           (submod model-base-path schema-info))

         (list
           (defmodule model-base-path)

           (para "This is the schema for " (~a 'model-base-path) ".  It was auto-generated by " (racket define-schema))

           (codeblock
             (pretty-format schema-info))))]))

