#lang racket

(provide auto-doc-model)

(require scribble/manual
         syntax/parse/define
         (for-syntax english
                     webapp/environment/util
                     racket/syntax)) 

(define-syntax (auto-doc-model stx)
  (syntax-parse stx
    [(_ model-name)
     (define singular-name (syntax->datum #'model-name))
     (define plural-name (plural singular-name))
     (define module-path 
       (format-id #'model-name
         "~a/models/~a/base"
         (pkg-name)
         plural-name))

     (define prefix:
       (format-id #'model-name
         "~a:"
         singular-name))

     (define prefix:schema-info
       (format-id #'model-name
         "~aschema-info"
         prefix:))

     #`(let ()
         (local-require 
           (submod #,module-path schema-info))

         (list
           (defmodule #,module-path)

           (para "This is the schema for " #,plural-name ".  It was auto-generated by " (racket define-schema))

           (codeblock
             (pretty-format schema-info)))) ]))

